### ISSUE TITLE
date range definition 

### ISSUE THREAD

**Issue by weloveconstance** [teamdatatonic/looker-date-comparison#5]
Hey, I wanted to implement this PoP analysis in my project but I am having a hard time here. Could you please tell me, in the script

dimension: days_in_period {
    description: "Gives the number of days in the current period date range"
    type: number
    sql: DATE_DIFF(DATE({% date_end current_date_range %}), DATE({% date_start current_date_range %}), DAY) ;;
    hidden:  yes
  }

Here how you can recognize the date start and the date end? Will the system recognize automatically when a user input a date range?  
We are using MSSQL, so I also need to migrate the bigquery to mssql as well. I saw that date start and date end appear many times in the code but should I give a definition somewhere? 

Looking forward to your feedback. 

![image](https://user-images.githubusercontent.com/61056484/74541846-b0bf8a00-4f42-11ea-98e7-3bbc7bff473d.png)

**Comment by ghost** [comment]
hello. we just made an update to code which changes this section of the code. It is now using looker dimension group as an object, and using liquid syntax. therefore its no longer dependent on any sql dialect (i think). please try the new code and let me know of any issues

The user will input a date start and date end through the filters defined at the top of the view file. these are referenced here in the liquid syntax, looker inputs the values of these filters into the SQL

**Comment by weloveconstance** [comment]
Hey Jamie,

Thanks for helping. I do have another thing that might need your opinion. In our project, we only interested in the date_date. We are not going to grabbing the data from the database detailed into TIME level. I noticed that you have changed the function into TIMESTAMP, since we are based on mssql, could I still use date_add or it will affect the code from executing? Should I change the date type all into date?  I'm looking forward to your feedback. Thank you in advance.

Bests.


________________________________
发件人: Jamie <notifications@github.com>
发送时间: 2020年2月14日 17:45
收件人: teamdatatonic/looker-date-comparison <looker-date-comparison@noreply.github.com>
抄送: weloveconstance <ziyiself@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [teamdatatonic/looker-date-comparison] date range definition (#5)


hello. we just made an update to code which changes this section of the code. It is now using looker dimension group as an object, and using liquid syntax. therefore its no longer dependent on any sql dialect (i think). please try the new code and let me know of any issues

The user will input a date start and date end through the filters defined at the top of the view file. these are referenced here in the liquid syntax, looker inputs the values of these filters into the SQL

―

**Comment by weloveconstance** [comment]
Problem solved! Thank you!.

**Comment by brockmueller** [comment]
Hey Jamie,
thanks for helping us and updating the code.

We have it working now and it is going to be super helpful.
Please extend the thanks to all involved in this project.

Best,
Marcelli Brockmüller
